package com.app.sportify_backend.models;

public enum NotificationType {
    INVITATION_ACCEPTED,
    INVITATION_REJECTED,
    TEAM_JOINED,
    MATCH_COMPLETED,
    PLAYER_JOINED_MATCH,
    RESERVATION_REQUEST,
    RESERVATION_CONFIRMED,
    RESERVATION_REJECTED,
    RESERVATION_CANCELLED,
    RESERVATION_REMINDER,
    TEAM_LEFT
}


